require "o_data/abstract_schema/base"
require "o_data/abstract_schema/entity_type"
require "o_data/abstract_schema/property"
require "o_data/abstract_schema/navigation_property"
require "o_data/abstract_schema/association"
